"""Utility functions for MS²Rescore report generation."""

import logging
from collections import defaultdict
from csv import DictReader
from pathlib import Path
from typing import Dict, Optional, Tuple

import pandas as pd
import psm_utils
from mokapot import LinearConfidence, LinearPsmDataset, read_fasta

from ms2rescore.exceptions import ReportGenerationError

logger = logging.getLogger(__name__)


def read_feature_names(feature_names_path: Optional[Path]) -> dict:
    """Read feature names and mapping with feature generator from file."""
    feature_names = defaultdict(list)
    if not feature_names_path or not feature_names_path.is_file():
        return feature_names

    try:
        with open(feature_names_path) as f:
            reader = DictReader(f, delimiter="\t")
            for line in reader:
                feature_names[line["feature_generator"]].append(line["feature_name"])
    except (FileNotFoundError, KeyError, ValueError) as e:
        logger.warning(f"Could not read feature names file: {e}")

    return feature_names


def infer_feature_names_from_psm_list(psm_list: psm_utils.PSMList) -> Dict[str, list]:
    """Infer feature names and generators from PSM list when no feature_names file exists."""
    feature_names = defaultdict(list)

    if not psm_list or not psm_list[0].rescoring_features:
        return feature_names

    # Get all feature names from the first PSM
    all_features = list(psm_list[0].rescoring_features.keys())

    # Try to infer generator from feature name patterns
    for fname in all_features:
        fname_lower = fname.lower()

        # Pattern matching for common feature generators
        if any(x in fname_lower for x in ["ms2pip", "spec_pearson", "spec_spearman", "ionmatch"]):
            feature_names["ms2pip"].append(fname)
        elif any(x in fname_lower for x in ["deeplc", "retention_time", "rt_diff"]):
            feature_names["deeplc"].append(fname)
        elif any(
            x in fname_lower for x in ["im2deep", "ccs_predicted_im2deep", "ccs_observed_im2deep"]
        ):
            feature_names["im2deep"].append(fname)
        elif (
            any(x in fname_lower for x in ["ionmob", "ccs_predicted", "ccs_observed"])
            and "im2deep" not in fname_lower
        ):
            feature_names["ionmob"].append(fname)
        elif any(x in fname_lower for x in ["basic", "charge", "missed_cleavages"]):
            feature_names["basic"].append(fname)
        else:
            # Unknown generator - use "other" category
            feature_names["other"].append(fname)

    return feature_names


def get_feature_values(
    psm_list: psm_utils.PSMList, feature_names: Optional[list] = None
) -> pd.DataFrame:
    """Get feature values for all PSMs in a PSM list."""
    if not feature_names:
        feature_names = list(psm_list[0].rescoring_features.keys())
    features = pd.DataFrame(
        {fname: psm.rescoring_features[fname] for fname in feature_names} for psm in psm_list
    ).astype("float32")
    return features


def get_confidence_estimates(
    psm_list: psm_utils.PSMList, fasta_file: Optional[str] = None
) -> Tuple[LinearConfidence, LinearConfidence]:
    """Return identification confidence before and after rescoring."""
    try:
        score_before = pd.DataFrame.from_records(psm_list["provenance_data"])[
            "before_rescoring_score"
        ].astype(float)
    except KeyError as e:
        raise ReportGenerationError(
            "No `before_rescoring_score` in PSM list provenance data. Ensure that the PSM list "
            "was generated by MS²Rescore. Could not generate report."
        ) from e

    score_after = psm_list["score"]
    peptide = (
        pd.Series(psm_list["peptidoform"]).astype(str).str.replace(r"(/\d+$)", "", n=1, regex=True)
    )
    psms = pd.DataFrame({"peptide": peptide, "is_target": ~psm_list["is_decoy"]}).reset_index()
    lin_psm_dataset = LinearPsmDataset(
        psms=psms,
        target_column="is_target",
        spectrum_columns="index",
        peptide_column="peptide",
    )
    if fasta_file:
        fasta = read_fasta(fasta_file)
        lin_psm_dataset.add_proteins(fasta)

    confidence = dict()
    for when, scores in [("before", score_before), ("after", score_after)]:
        try:
            confidence[when] = lin_psm_dataset.assign_confidence(scores=scores)
        except (RuntimeError, IndexError):
            confidence[when] = None
            logger.warning("Could not assign confidence estimates for %s rescoring.", when)

    return confidence["before"], confidence["after"]


def create_psm_dataframe(psm_list: psm_utils.PSMList) -> pd.DataFrame:
    """
    Create a comprehensive dataframe from PSM list with all necessary information.

    This dataframe includes:
    - Basic PSM information (peptide, score, qvalue, is_decoy, etc.)
    - Before rescoring scores from provenance data
    - All rescoring features

    Parameters
    ----------
    psm_list
        PSM list to convert to dataframe.

    Returns
    -------
    pd.DataFrame
        Dataframe with all PSM information.
    """
    # Start with basic PSM dataframe
    psm_df = psm_list.to_dataframe()

    # Add before rescoring scores from provenance data
    try:
        provenance_df = pd.DataFrame.from_records(psm_list["provenance_data"])
        if "before_rescoring_score" in provenance_df.columns:
            psm_df["score_before"] = provenance_df["before_rescoring_score"].astype(float)
        if "before_rescoring_qvalue" in provenance_df.columns:
            psm_df["qvalue_before"] = provenance_df["before_rescoring_qvalue"].astype(float)
    except (KeyError, ValueError) as e:
        logger.warning("Could not extract before rescoring scores from provenance data: %s", e)
        psm_df["score_before"] = None
        psm_df["qvalue_before"] = None

    # Add rescoring features - vectorized extraction
    if psm_list[0].rescoring_features:
        # Extract all rescoring_features dicts at once (much faster than looping)
        features_df = pd.DataFrame.from_records(psm_list["rescoring_features"]).astype("float32")
        # Merge features with PSM dataframe (they should have same index)
        psm_df = pd.concat([psm_df, features_df], axis=1)
        # Remove duplicate columns (keep last, i.e., from features_df)
        psm_df = psm_df.loc[:, ~psm_df.columns.duplicated(keep="last")]

    # Rename current score/qvalue to score_after/qvalue_after for clarity
    psm_df["score_after"] = psm_df["score"]
    psm_df["qvalue_after"] = psm_df["qvalue"]

    return psm_df


def calculate_fdr_stats(
    psm_df: pd.DataFrame,
    score_column: str = "score",
    fdr_threshold: float = 0.01,
) -> Dict[str, int]:
    """
    Calculate FDR statistics from PSM dataframe.

    Parameters
    ----------
    psm_df
        Dataframe with PSM information including score, qvalue, and is_decoy columns.
    score_column
        Column name for scores to use.
    fdr_threshold
        FDR threshold for counting identifications.

    Returns
    -------
    dict
        Dictionary with counts of identifications at different levels.
    """
    stats = {}

    # PSM level
    targets = psm_df[~psm_df["is_decoy"]]
    stats["psms"] = len(targets[targets["qvalue"] <= fdr_threshold])

    # Peptide level (unique peptide sequences)
    if "peptidoform" in psm_df.columns:
        unique_peptides = targets[targets["qvalue"] <= fdr_threshold]["peptidoform"].nunique()
        stats["peptides"] = unique_peptides

    return stats


def get_score_threshold_at_fdr(
    psm_df: pd.DataFrame,
    score_column: str = "score",
    qvalue_column: str = "qvalue",
    fdr_threshold: float = 0.01,
) -> Optional[float]:
    """
    Get score threshold at a given FDR threshold.

    Parameters
    ----------
    psm_df
        Dataframe with PSM information.
    score_column
        Column name for scores.
    qvalue_column
        Column name for q-values.
    fdr_threshold
        FDR threshold.

    Returns
    -------
    float or None
        Score threshold at the FDR threshold, or None if no PSMs pass threshold.
    """
    try:
        threshold = (
            psm_df[psm_df[qvalue_column] <= fdr_threshold]
            .sort_values(qvalue_column, ascending=False)[score_column]
            .iloc[0]
        )
        return threshold
    except (IndexError, KeyError):
        return None
